site_name: SimpleStore
repo_name: SimpleStore
repo_url: https://github.com/uber/simple-store
site_description: "Simple yet performant asynchronous file storage for Android"
site_author: Uber Technologies
remote_branch: gh-pages

copyright: 'Copyright &copy; 2019 Uber Technologies'

theme:
  name: 'material'
  favicon: images/uber_oss_logo.png
  logo: images/uber_oss_logo.png
  palette:
    primary: 'white'
    accent: 'white'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - '0.X API':
    - 'SimpleStore': 0.x/simplestore/index.html
    - 'SimpleStore for Protocol Buffers': 0.x/protosimplestore/index.html
    - 'Testing SimpleStore': 0.x/testing/index.html
  - 'Changelog' : changelog.md
  - 'Contributing': contributing.md
  - 'Code of Conduct': code-of-conduct.md
